apis:
  - host: api.example.com
    url: /users
    method: GET
    parameters:
      limit: 10
    headers:
      Authorization: "Bearer example-token"
    mapping:
      - header: "User ID"
        path: "id"
      - header: "Name"
        path: "name"
      - header: "Email"
        path: "email"
  
  - host: api.example.com
    url: /orders
    method: GET
    parameters:
      status: "completed"
    headers:
      Authorization: "Bearer example-token"
    mapping:
      - header: "Order ID"
        path: "orderId"
      - header: "Amount"
        path: "totalAmount"
      - header: "Status"
        path: "status" 