apis:
  - method: GET
    url: /boa/api
    parameters: {}
    headers:
      X-Qlik: '1234'
      SSO_USER: '1234'
    mapping:
      - source: "data[*].id"
        target: "id"
      - source: "data[*].name"
        target: "name"
    host: 10.12.12.12:8080
