apis:
  - id: "get_posts"
    method: GET
    url: /posts
    parameters: {}
    headers: {}
    mapping:
      - source: "id"
        target: "post_id"
      - source: "title"
        target: "title"
      - source: "userId"
        target: "user_id"
    host: jsonplaceholder.typicode.com
