apis:
  - id: get-posts
    name: 게시물 목록 조회
    description: JSONPlaceholder의 게시물 목록을 조회합니다
    method: GET
    url: https://jsonplaceholder.typicode.com/posts
    headers:
      Content-Type: application/json
    mapping:
      - from: id
        to: 게시물ID
      - from: userId
        to: 작성자ID
      - from: title
        to: 제목
      - from: body
        to: 내용

  - id: get-comments
    name: 댓글 목록 조회
    description: JSONPlaceholder의 댓글 목록을 조회합니다
    method: GET
    url: https://jsonplaceholder.typicode.com/comments
    headers:
      Content-Type: application/json
    mapping:
      - from: id
        to: 댓글ID
      - from: postId
        to: 게시물ID
      - from: name
        to: 작성자
      - from: email
        to: 이메일
      - from: body
        to: 내용 