apis:
  - host: api.example.com
    url: /users
    method: GET
    parameters:
      limit: '10'
    headers:
      Authorization: Bearer token123
    mapping: []
  - host: api.example.com
    url: /orders
    method: POST
    parameters: {}
    headers:
      Content-Type: application/json
      Authorization: Bearer token123
    mapping: []
  - host: api.example.com
    url: /products
    method: GET
    parameters: {}
    headers:
      Accept: application/json
      X-API-Key: abc123
    mapping: []
